import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import { requireWorkspaceAccess } from './session.server'
import { getSummaryImpl, getPlatformTableImpl, getTopPostsImpl } from './analytics.server'
import type { AnalyticsRange, CustomRange } from './analytics.server'

export async function buildAnalyticsPdf(
  slug: string,
  range: AnalyticsRange,
  accountId: string | null = null,
  custom: CustomRange = null,
): Promise<Buffer> {
  const { workspace } = await requireWorkspaceAccess(slug).then((r) => {
    if (!r.ok) throw new Error(r.reason)
    return r
  })

  const [summary, platformTable, topPosts] = await Promise.all([
    getSummaryImpl(slug, range, accountId, custom),
    getPlatformTableImpl(slug, range, custom),
    getTopPostsImpl(slug, range, custom, 10),
  ])

  const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()
  const today = new Date().toISOString().slice(0, 10)

  const rangeLabel =
    range === 'custom' && custom
      ? `${custom.fromIso.slice(0, 10)} — ${custom.toIso.slice(0, 10)}`
      : range === '7d'
        ? 'Last 7 days'
        : range === '30d'
          ? 'Last 30 days'
          : 'Last 90 days'

  function addFooter() {
    const pages = doc.getNumberOfPages()
    for (let i = 1; i <= pages; i++) {
      doc.setPage(i)
      doc.setFontSize(8)
      doc.setTextColor(160, 160, 160)
      doc.text(`Generated by Nova · ${today}`, pageW / 2, pageH - 20, {
        align: 'center',
      })
    }
  }

  // ── Page 1: Cover ───────────────────────────────────────
  doc.setFontSize(32)
  doc.setTextColor(30, 30, 30)
  doc.text(workspace.name, pageW / 2, pageH / 2 - 40, { align: 'center' })

  doc.setFontSize(18)
  doc.setTextColor(100, 100, 100)
  doc.text('Analytics Report', pageW / 2, pageH / 2, { align: 'center' })

  doc.setFontSize(12)
  doc.setTextColor(140, 140, 140)
  doc.text(rangeLabel, pageW / 2, pageH / 2 + 30, { align: 'center' })

  // ── Page 2: Summary ─────────────────────────────────────
  doc.addPage()
  doc.setFontSize(18)
  doc.setTextColor(30, 30, 30)
  doc.text('Summary', 40, 50)

  const stats = [
    { label: 'Followers', value: summary.followerGrowth.toLocaleString() },
    { label: 'Reach', value: summary.totalReach.toLocaleString() },
    { label: 'Impressions', value: '—' }, // impressions not on summary; use reach/engagements
    { label: 'Engagements', value: summary.totalEngagements.toLocaleString() },
    { label: 'Likes', value: '—' },
    { label: 'Clicks', value: '—' },
  ]

  // Fill impressions/likes/clicks from platform table totals
  let totalImpressions = 0
  let totalLikes = 0
  let totalClicks = 0
  for (const row of platformTable) {
    totalImpressions += row.impressions
    totalLikes += row.likes
    totalClicks += row.clicks
  }
  stats[2]!.value = totalImpressions.toLocaleString()
  stats[4]!.value = totalLikes.toLocaleString()
  stats[5]!.value = totalClicks.toLocaleString()

  const cols = 3
  const boxW = (pageW - 80 - 20) / cols
  const boxH = 60

  for (let i = 0; i < stats.length; i++) {
    const col = i % cols
    const row = Math.floor(i / cols)
    const x = 40 + col * (boxW + 10)
    const y = 80 + row * (boxH + 10)

    doc.setDrawColor(220, 220, 220)
    doc.setFillColor(250, 250, 250)
    doc.roundedRect(x, y, boxW, boxH, 4, 4, 'FD')

    doc.setFontSize(9)
    doc.setTextColor(130, 130, 130)
    doc.text(stats[i]!.label, x + 10, y + 18)

    doc.setFontSize(18)
    doc.setTextColor(30, 30, 30)
    doc.text(stats[i]!.value, x + 10, y + 42)
  }

  // ── Page 3: Platform Table ──────────────────────────────
  doc.addPage()
  doc.setFontSize(18)
  doc.setTextColor(30, 30, 30)
  doc.text('Platform Breakdown', 40, 50)

  autoTable(doc as Parameters<typeof autoTable>[0], {
    startY: 70,
    head: [['Platform', 'Posts', 'Reach', 'Impressions', 'Engagements', 'Eng. Rate']],
    body: platformTable.map((r) => [
      `${r.platform} @${r.accountHandle}`,
      r.posts.toString(),
      r.reach.toLocaleString(),
      r.impressions.toLocaleString(),
      (r.likes + r.comments + r.shares + r.clicks).toLocaleString(),
      `${r.engagementRate.toFixed(1)}%`,
    ]),
    styles: { fontSize: 9, cellPadding: 6 },
    headStyles: { fillColor: [99, 102, 241] },
  })

  // ── Page 4: Top Posts ───────────────────────────────────
  doc.addPage()
  doc.setFontSize(18)
  doc.setTextColor(30, 30, 30)
  doc.text('Top Posts', 40, 50)

  autoTable(doc as Parameters<typeof autoTable>[0], {
    startY: 70,
    head: [['Content', 'Platforms', 'Likes', 'Comments', 'Shares', 'Engagements']],
    body: topPosts.map((p) => [
      (p.content || '(no text)').slice(0, 80) + (p.content && p.content.length > 80 ? '...' : ''),
      p.platforms.join(', '),
      p.likes.toString(),
      p.comments.toString(),
      p.shares.toString(),
      p.engagements.toString(),
    ]),
    styles: { fontSize: 9, cellPadding: 6 },
    headStyles: { fillColor: [99, 102, 241] },
    columnStyles: { 0: { cellWidth: 200 } },
  })

  addFooter()

  const arrayBuffer = doc.output('arraybuffer')
  return Buffer.from(arrayBuffer)
}
