/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ReviewTokenRouteImport } from './routes/review/$token'
import { Route as LSlugRouteImport } from './routes/l/$slug'
import { Route as DigestUnsubscribeRouteImport } from './routes/digest/unsubscribe'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as BioHandleRouteImport } from './routes/bio/$handle'
import { Route as AdminWebhooksRouteImport } from './routes/admin/webhooks'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminPlansRouteImport } from './routes/admin/plans'
import { Route as AdminLoginsRouteImport } from './routes/admin/logins'
import { Route as AdminJobsRouteImport } from './routes/admin/jobs'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminApiKeysRouteImport } from './routes/admin/api-keys'
import { Route as DashboardWorkspaceSlugRouteImport } from './routes/_dashboard/$workspaceSlug'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AdminWorkspacesIndexRouteImport } from './routes/admin/workspaces/index'
import { Route as DashboardWorkspaceSlugIndexRouteImport } from './routes/_dashboard/$workspaceSlug/index'
import { Route as ApiV1PostsRouteImport } from './routes/api/v1/posts'
import { Route as ApiV1MediaRouteImport } from './routes/api/v1/media'
import { Route as ApiV1CampaignsRouteImport } from './routes/api/v1/campaigns'
import { Route as ApiV1AnalyticsRouteImport } from './routes/api/v1/analytics'
import { Route as ApiV1AccountsRouteImport } from './routes/api/v1/accounts'
import { Route as ApiReportsAnalyticsRouteImport } from './routes/api/reports/analytics'
import { Route as ApiPostsExportRouteImport } from './routes/api/posts/export'
import { Route as ApiNotificationsUnreadCountRouteImport } from './routes/api/notifications/unread-count'
import { Route as ApiMediaUploadRouteImport } from './routes/api/media/upload'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiHashtagsRouteImport } from './routes/api/ai/hashtags'
import { Route as ApiAiGenerateRouteImport } from './routes/api/ai/generate'
import { Route as ApiActivityExportRouteImport } from './routes/api/activity/export'
import { Route as ApiAccountExportRouteImport } from './routes/api/account/export'
import { Route as AdminWorkspacesWorkspaceIdRouteImport } from './routes/admin/workspaces/$workspaceId'
import { Route as DashboardWorkspaceSlugTemplatesRouteImport } from './routes/_dashboard/$workspaceSlug/templates'
import { Route as DashboardWorkspaceSlugTeamRouteImport } from './routes/_dashboard/$workspaceSlug/team'
import { Route as DashboardWorkspaceSlugNotificationsRouteImport } from './routes/_dashboard/$workspaceSlug/notifications'
import { Route as DashboardWorkspaceSlugMonitorsRouteImport } from './routes/_dashboard/$workspaceSlug/monitors'
import { Route as DashboardWorkspaceSlugMediaRouteImport } from './routes/_dashboard/$workspaceSlug/media'
import { Route as DashboardWorkspaceSlugInboxRouteImport } from './routes/_dashboard/$workspaceSlug/inbox'
import { Route as DashboardWorkspaceSlugComposeRouteImport } from './routes/_dashboard/$workspaceSlug/compose'
import { Route as DashboardWorkspaceSlugCalendarRouteImport } from './routes/_dashboard/$workspaceSlug/calendar'
import { Route as DashboardWorkspaceSlugApprovalsRouteImport } from './routes/_dashboard/$workspaceSlug/approvals'
import { Route as DashboardWorkspaceSlugAnalyticsRouteImport } from './routes/_dashboard/$workspaceSlug/analytics'
import { Route as DashboardWorkspaceSlugActivityRouteImport } from './routes/_dashboard/$workspaceSlug/activity'
import { Route as DashboardWorkspaceSlugAccountsRouteImport } from './routes/_dashboard/$workspaceSlug/accounts'
import { Route as ApiAdminQueuesIndexRouteImport } from './routes/api/admin/queues.index'
import { Route as DashboardWorkspaceSlugSettingsIndexRouteImport } from './routes/_dashboard/$workspaceSlug/settings/index'
import { Route as DashboardWorkspaceSlugPostsIndexRouteImport } from './routes/_dashboard/$workspaceSlug/posts/index'
import { Route as ApiV1PostsIdRouteImport } from './routes/api/v1/posts.$id'
import { Route as ApiV1OpenapiJsonRouteImport } from './routes/api/v1/openapi.json'
import { Route as ApiV1MediaIdRouteImport } from './routes/api/v1/media.$id'
import { Route as ApiV1CampaignsIdRouteImport } from './routes/api/v1/campaigns.$id'
import { Route as ApiOauthCallbackPlatformRouteImport } from './routes/api/oauth/callback/$platform'
import { Route as ApiCalendarTokenIcsRouteImport } from './routes/api/calendar/$token.ics'
import { Route as ApiBillingWebhookProviderRouteImport } from './routes/api/billing/webhook/$provider'
import { Route as ApiAdminUsersExportRouteImport } from './routes/api/admin/users.export'
import { Route as ApiAdminQueuesSplatRouteImport } from './routes/api/admin/queues.$'
import { Route as DashboardWorkspaceSlugTemplatesSeriesRouteImport } from './routes/_dashboard/$workspaceSlug/templates/series'
import { Route as DashboardWorkspaceSlugSettingsWhiteLabelRouteImport } from './routes/_dashboard/$workspaceSlug/settings/white-label'
import { Route as DashboardWorkspaceSlugSettingsSecurityRouteImport } from './routes/_dashboard/$workspaceSlug/settings/security'
import { Route as DashboardWorkspaceSlugSettingsScheduleRouteImport } from './routes/_dashboard/$workspaceSlug/settings/schedule'
import { Route as DashboardWorkspaceSlugSettingsRssRouteImport } from './routes/_dashboard/$workspaceSlug/settings/rss'
import { Route as DashboardWorkspaceSlugSettingsRepliesRouteImport } from './routes/_dashboard/$workspaceSlug/settings/replies'
import { Route as DashboardWorkspaceSlugSettingsNotificationsRouteImport } from './routes/_dashboard/$workspaceSlug/settings/notifications'
import { Route as DashboardWorkspaceSlugSettingsBioRouteImport } from './routes/_dashboard/$workspaceSlug/settings/bio'
import { Route as DashboardWorkspaceSlugSettingsBillingRouteImport } from './routes/_dashboard/$workspaceSlug/settings/billing'
import { Route as DashboardWorkspaceSlugSettingsApiRouteImport } from './routes/_dashboard/$workspaceSlug/settings/api'
import { Route as DashboardWorkspaceSlugSettingsAiRouteImport } from './routes/_dashboard/$workspaceSlug/settings/ai'
import { Route as DashboardWorkspaceSlugPostsCampaignsCampaignIdRouteImport } from './routes/_dashboard/$workspaceSlug/posts/campaigns/$campaignId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ReviewTokenRoute = ReviewTokenRouteImport.update({
  id: '/review/$token',
  path: '/review/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LSlugRoute = LSlugRouteImport.update({
  id: '/l/$slug',
  path: '/l/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DigestUnsubscribeRoute = DigestUnsubscribeRouteImport.update({
  id: '/digest/unsubscribe',
  path: '/digest/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BioHandleRoute = BioHandleRouteImport.update({
  id: '/bio/$handle',
  path: '/bio/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebhooksRoute = AdminWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginsRoute = AdminLoginsRouteImport.update({
  id: '/logins',
  path: '/logins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiKeysRoute = AdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardWorkspaceSlugRoute = DashboardWorkspaceSlugRouteImport.update({
  id: '/$workspaceSlug',
  path: '/$workspaceSlug',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AdminWorkspacesIndexRoute = AdminWorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardWorkspaceSlugIndexRoute =
  DashboardWorkspaceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardWorkspaceSlugRoute,
  } as any)
const ApiV1PostsRoute = ApiV1PostsRouteImport.update({
  id: '/api/v1/posts',
  path: '/api/v1/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MediaRoute = ApiV1MediaRouteImport.update({
  id: '/api/v1/media',
  path: '/api/v1/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CampaignsRoute = ApiV1CampaignsRouteImport.update({
  id: '/api/v1/campaigns',
  path: '/api/v1/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AnalyticsRoute = ApiV1AnalyticsRouteImport.update({
  id: '/api/v1/analytics',
  path: '/api/v1/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AccountsRoute = ApiV1AccountsRouteImport.update({
  id: '/api/v1/accounts',
  path: '/api/v1/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsAnalyticsRoute = ApiReportsAnalyticsRouteImport.update({
  id: '/api/reports/analytics',
  path: '/api/reports/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsExportRoute = ApiPostsExportRouteImport.update({
  id: '/api/posts/export',
  path: '/api/posts/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsUnreadCountRoute =
  ApiNotificationsUnreadCountRouteImport.update({
    id: '/api/notifications/unread-count',
    path: '/api/notifications/unread-count',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMediaUploadRoute = ApiMediaUploadRouteImport.update({
  id: '/api/media/upload',
  path: '/api/media/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiHashtagsRoute = ApiAiHashtagsRouteImport.update({
  id: '/api/ai/hashtags',
  path: '/api/ai/hashtags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateRoute = ApiAiGenerateRouteImport.update({
  id: '/api/ai/generate',
  path: '/api/ai/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActivityExportRoute = ApiActivityExportRouteImport.update({
  id: '/api/activity/export',
  path: '/api/activity/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountExportRoute = ApiAccountExportRouteImport.update({
  id: '/api/account/export',
  path: '/api/account/export',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkspacesWorkspaceIdRoute =
  AdminWorkspacesWorkspaceIdRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => AdminRoute,
  } as any)
const DashboardWorkspaceSlugTemplatesRoute =
  DashboardWorkspaceSlugTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => DashboardWorkspaceSlugRoute,
  } as any)
const DashboardWorkspaceSlugTeamRoute =
  DashboardWorkspaceSlugTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => DashboardWorkspaceSlugRoute,
  } as any)
const DashboardWorkspaceSlugNotificationsRoute =
  DashboardWorkspaceSlugNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardWorkspaceSlugRoute,
  } as any)
const DashboardWorkspaceSlugMonitorsRoute =
  DashboardWorkspaceSlugMonitorsRouteImport.update({
    id: '/monitors',
    path: '/monitors',
    getParentRoute: () => DashboardWorkspaceSlugRoute,
  } as any)
const DashboardWorkspaceSlugMediaRoute =
  DashboardWorkspaceSlugMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => DashboardWorkspaceSlugRoute,
  } as any)
const DashboardWorkspaceSlugInboxRoute =
  DashboardWorkspaceSlugInboxRouteImport.update({
    id: '/inbox',
    path: '/inbox',
    getParentRoute: () => DashboardWorkspaceSlugRoute,
  } as any)
const DashboardWorkspaceSlugComposeRoute =
  DashboardWorkspaceSlugComposeRouteImport.update({
    id: '/compose',
    path: '/compose',
    getParentRoute: () => DashboardWorkspaceSlugRoute,
  } as any)
const DashboardWorkspaceSlugCalendarRoute =
  DashboardWorkspaceSlugCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => DashboardWorkspaceSlugRoute,
  } as any)
const DashboardWorkspaceSlugApprovalsRoute =
  DashboardWorkspaceSlugApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => DashboardWorkspaceSlugRoute,
  } as any)
const DashboardWorkspaceSlugAnalyticsRoute =
  DashboardWorkspaceSlugAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => DashboardWorkspaceSlugRoute,
  } as any)
const DashboardWorkspaceSlugActivityRoute =
  DashboardWorkspaceSlugActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => DashboardWorkspaceSlugRoute,
  } as any)
const DashboardWorkspaceSlugAccountsRoute =
  DashboardWorkspaceSlugAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => DashboardWorkspaceSlugRoute,
  } as any)
const ApiAdminQueuesIndexRoute = ApiAdminQueuesIndexRouteImport.update({
  id: '/api/admin/queues/',
  path: '/api/admin/queues/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkspaceSlugSettingsIndexRoute =
  DashboardWorkspaceSlugSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => DashboardWorkspaceSlugRoute,
  } as any)
const DashboardWorkspaceSlugPostsIndexRoute =
  DashboardWorkspaceSlugPostsIndexRouteImport.update({
    id: '/posts/',
    path: '/posts/',
    getParentRoute: () => DashboardWorkspaceSlugRoute,
  } as any)
const ApiV1PostsIdRoute = ApiV1PostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1PostsRoute,
} as any)
const ApiV1OpenapiJsonRoute = ApiV1OpenapiJsonRouteImport.update({
  id: '/api/v1/openapi/json',
  path: '/api/v1/openapi/json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MediaIdRoute = ApiV1MediaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1MediaRoute,
} as any)
const ApiV1CampaignsIdRoute = ApiV1CampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1CampaignsRoute,
} as any)
const ApiOauthCallbackPlatformRoute =
  ApiOauthCallbackPlatformRouteImport.update({
    id: '/api/oauth/callback/$platform',
    path: '/api/oauth/callback/$platform',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCalendarTokenIcsRoute = ApiCalendarTokenIcsRouteImport.update({
  id: '/api/calendar/$token/ics',
  path: '/api/calendar/$token/ics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingWebhookProviderRoute =
  ApiBillingWebhookProviderRouteImport.update({
    id: '/api/billing/webhook/$provider',
    path: '/api/billing/webhook/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminUsersExportRoute = ApiAdminUsersExportRouteImport.update({
  id: '/api/admin/users/export',
  path: '/api/admin/users/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminQueuesSplatRoute = ApiAdminQueuesSplatRouteImport.update({
  id: '/api/admin/queues/$',
  path: '/api/admin/queues/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkspaceSlugTemplatesSeriesRoute =
  DashboardWorkspaceSlugTemplatesSeriesRouteImport.update({
    id: '/series',
    path: '/series',
    getParentRoute: () => DashboardWorkspaceSlugTemplatesRoute,
  } as any)
const DashboardWorkspaceSlugSettingsWhiteLabelRoute =
  DashboardWorkspaceSlugSettingsWhiteLabelRouteImport.update({
    id: '/settings/white-label',
    path: '/settings/white-label',
    getParentRoute: () => DashboardWorkspaceSlugRoute,
  } as any)
const DashboardWorkspaceSlugSettingsSecurityRoute =
  DashboardWorkspaceSlugSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => DashboardWorkspaceSlugRoute,
  } as any)
const DashboardWorkspaceSlugSettingsScheduleRoute =
  DashboardWorkspaceSlugSettingsScheduleRouteImport.update({
    id: '/settings/schedule',
    path: '/settings/schedule',
    getParentRoute: () => DashboardWorkspaceSlugRoute,
  } as any)
const DashboardWorkspaceSlugSettingsRssRoute =
  DashboardWorkspaceSlugSettingsRssRouteImport.update({
    id: '/settings/rss',
    path: '/settings/rss',
    getParentRoute: () => DashboardWorkspaceSlugRoute,
  } as any)
const DashboardWorkspaceSlugSettingsRepliesRoute =
  DashboardWorkspaceSlugSettingsRepliesRouteImport.update({
    id: '/settings/replies',
    path: '/settings/replies',
    getParentRoute: () => DashboardWorkspaceSlugRoute,
  } as any)
const DashboardWorkspaceSlugSettingsNotificationsRoute =
  DashboardWorkspaceSlugSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => DashboardWorkspaceSlugRoute,
  } as any)
const DashboardWorkspaceSlugSettingsBioRoute =
  DashboardWorkspaceSlugSettingsBioRouteImport.update({
    id: '/settings/bio',
    path: '/settings/bio',
    getParentRoute: () => DashboardWorkspaceSlugRoute,
  } as any)
const DashboardWorkspaceSlugSettingsBillingRoute =
  DashboardWorkspaceSlugSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => DashboardWorkspaceSlugRoute,
  } as any)
const DashboardWorkspaceSlugSettingsApiRoute =
  DashboardWorkspaceSlugSettingsApiRouteImport.update({
    id: '/settings/api',
    path: '/settings/api',
    getParentRoute: () => DashboardWorkspaceSlugRoute,
  } as any)
const DashboardWorkspaceSlugSettingsAiRoute =
  DashboardWorkspaceSlugSettingsAiRouteImport.update({
    id: '/settings/ai',
    path: '/settings/ai',
    getParentRoute: () => DashboardWorkspaceSlugRoute,
  } as any)
const DashboardWorkspaceSlugPostsCampaignsCampaignIdRoute =
  DashboardWorkspaceSlugPostsCampaignsCampaignIdRouteImport.update({
    id: '/posts/campaigns/$campaignId',
    path: '/posts/campaigns/$campaignId',
    getParentRoute: () => DashboardWorkspaceSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/admin': typeof AdminRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/onboarding': typeof OnboardingRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/$workspaceSlug': typeof DashboardWorkspaceSlugRouteWithChildren
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/logins': typeof AdminLoginsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/bio/$handle': typeof BioHandleRoute
  '/c/$token': typeof CTokenRoute
  '/digest/unsubscribe': typeof DigestUnsubscribeRoute
  '/l/$slug': typeof LSlugRoute
  '/review/$token': typeof ReviewTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/$workspaceSlug/accounts': typeof DashboardWorkspaceSlugAccountsRoute
  '/$workspaceSlug/activity': typeof DashboardWorkspaceSlugActivityRoute
  '/$workspaceSlug/analytics': typeof DashboardWorkspaceSlugAnalyticsRoute
  '/$workspaceSlug/approvals': typeof DashboardWorkspaceSlugApprovalsRoute
  '/$workspaceSlug/calendar': typeof DashboardWorkspaceSlugCalendarRoute
  '/$workspaceSlug/compose': typeof DashboardWorkspaceSlugComposeRoute
  '/$workspaceSlug/inbox': typeof DashboardWorkspaceSlugInboxRoute
  '/$workspaceSlug/media': typeof DashboardWorkspaceSlugMediaRoute
  '/$workspaceSlug/monitors': typeof DashboardWorkspaceSlugMonitorsRoute
  '/$workspaceSlug/notifications': typeof DashboardWorkspaceSlugNotificationsRoute
  '/$workspaceSlug/team': typeof DashboardWorkspaceSlugTeamRoute
  '/$workspaceSlug/templates': typeof DashboardWorkspaceSlugTemplatesRouteWithChildren
  '/admin/workspaces/$workspaceId': typeof AdminWorkspacesWorkspaceIdRoute
  '/api/account/export': typeof ApiAccountExportRoute
  '/api/activity/export': typeof ApiActivityExportRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/ai/hashtags': typeof ApiAiHashtagsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/notifications/unread-count': typeof ApiNotificationsUnreadCountRoute
  '/api/posts/export': typeof ApiPostsExportRoute
  '/api/reports/analytics': typeof ApiReportsAnalyticsRoute
  '/api/v1/accounts': typeof ApiV1AccountsRoute
  '/api/v1/analytics': typeof ApiV1AnalyticsRoute
  '/api/v1/campaigns': typeof ApiV1CampaignsRouteWithChildren
  '/api/v1/media': typeof ApiV1MediaRouteWithChildren
  '/api/v1/posts': typeof ApiV1PostsRouteWithChildren
  '/$workspaceSlug/': typeof DashboardWorkspaceSlugIndexRoute
  '/admin/workspaces/': typeof AdminWorkspacesIndexRoute
  '/$workspaceSlug/settings/ai': typeof DashboardWorkspaceSlugSettingsAiRoute
  '/$workspaceSlug/settings/api': typeof DashboardWorkspaceSlugSettingsApiRoute
  '/$workspaceSlug/settings/billing': typeof DashboardWorkspaceSlugSettingsBillingRoute
  '/$workspaceSlug/settings/bio': typeof DashboardWorkspaceSlugSettingsBioRoute
  '/$workspaceSlug/settings/notifications': typeof DashboardWorkspaceSlugSettingsNotificationsRoute
  '/$workspaceSlug/settings/replies': typeof DashboardWorkspaceSlugSettingsRepliesRoute
  '/$workspaceSlug/settings/rss': typeof DashboardWorkspaceSlugSettingsRssRoute
  '/$workspaceSlug/settings/schedule': typeof DashboardWorkspaceSlugSettingsScheduleRoute
  '/$workspaceSlug/settings/security': typeof DashboardWorkspaceSlugSettingsSecurityRoute
  '/$workspaceSlug/settings/white-label': typeof DashboardWorkspaceSlugSettingsWhiteLabelRoute
  '/$workspaceSlug/templates/series': typeof DashboardWorkspaceSlugTemplatesSeriesRoute
  '/api/admin/queues/$': typeof ApiAdminQueuesSplatRoute
  '/api/admin/users/export': typeof ApiAdminUsersExportRoute
  '/api/billing/webhook/$provider': typeof ApiBillingWebhookProviderRoute
  '/api/calendar/$token/ics': typeof ApiCalendarTokenIcsRoute
  '/api/oauth/callback/$platform': typeof ApiOauthCallbackPlatformRoute
  '/api/v1/campaigns/$id': typeof ApiV1CampaignsIdRoute
  '/api/v1/media/$id': typeof ApiV1MediaIdRoute
  '/api/v1/openapi/json': typeof ApiV1OpenapiJsonRoute
  '/api/v1/posts/$id': typeof ApiV1PostsIdRoute
  '/$workspaceSlug/posts/': typeof DashboardWorkspaceSlugPostsIndexRoute
  '/$workspaceSlug/settings/': typeof DashboardWorkspaceSlugSettingsIndexRoute
  '/api/admin/queues/': typeof ApiAdminQueuesIndexRoute
  '/$workspaceSlug/posts/campaigns/$campaignId': typeof DashboardWorkspaceSlugPostsCampaignsCampaignIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/healthz': typeof HealthzRoute
  '/onboarding': typeof OnboardingRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/logins': typeof AdminLoginsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/bio/$handle': typeof BioHandleRoute
  '/c/$token': typeof CTokenRoute
  '/digest/unsubscribe': typeof DigestUnsubscribeRoute
  '/l/$slug': typeof LSlugRoute
  '/review/$token': typeof ReviewTokenRoute
  '/admin': typeof AdminIndexRoute
  '/$workspaceSlug/accounts': typeof DashboardWorkspaceSlugAccountsRoute
  '/$workspaceSlug/activity': typeof DashboardWorkspaceSlugActivityRoute
  '/$workspaceSlug/analytics': typeof DashboardWorkspaceSlugAnalyticsRoute
  '/$workspaceSlug/approvals': typeof DashboardWorkspaceSlugApprovalsRoute
  '/$workspaceSlug/calendar': typeof DashboardWorkspaceSlugCalendarRoute
  '/$workspaceSlug/compose': typeof DashboardWorkspaceSlugComposeRoute
  '/$workspaceSlug/inbox': typeof DashboardWorkspaceSlugInboxRoute
  '/$workspaceSlug/media': typeof DashboardWorkspaceSlugMediaRoute
  '/$workspaceSlug/monitors': typeof DashboardWorkspaceSlugMonitorsRoute
  '/$workspaceSlug/notifications': typeof DashboardWorkspaceSlugNotificationsRoute
  '/$workspaceSlug/team': typeof DashboardWorkspaceSlugTeamRoute
  '/$workspaceSlug/templates': typeof DashboardWorkspaceSlugTemplatesRouteWithChildren
  '/admin/workspaces/$workspaceId': typeof AdminWorkspacesWorkspaceIdRoute
  '/api/account/export': typeof ApiAccountExportRoute
  '/api/activity/export': typeof ApiActivityExportRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/ai/hashtags': typeof ApiAiHashtagsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/notifications/unread-count': typeof ApiNotificationsUnreadCountRoute
  '/api/posts/export': typeof ApiPostsExportRoute
  '/api/reports/analytics': typeof ApiReportsAnalyticsRoute
  '/api/v1/accounts': typeof ApiV1AccountsRoute
  '/api/v1/analytics': typeof ApiV1AnalyticsRoute
  '/api/v1/campaigns': typeof ApiV1CampaignsRouteWithChildren
  '/api/v1/media': typeof ApiV1MediaRouteWithChildren
  '/api/v1/posts': typeof ApiV1PostsRouteWithChildren
  '/$workspaceSlug': typeof DashboardWorkspaceSlugIndexRoute
  '/admin/workspaces': typeof AdminWorkspacesIndexRoute
  '/$workspaceSlug/settings/ai': typeof DashboardWorkspaceSlugSettingsAiRoute
  '/$workspaceSlug/settings/api': typeof DashboardWorkspaceSlugSettingsApiRoute
  '/$workspaceSlug/settings/billing': typeof DashboardWorkspaceSlugSettingsBillingRoute
  '/$workspaceSlug/settings/bio': typeof DashboardWorkspaceSlugSettingsBioRoute
  '/$workspaceSlug/settings/notifications': typeof DashboardWorkspaceSlugSettingsNotificationsRoute
  '/$workspaceSlug/settings/replies': typeof DashboardWorkspaceSlugSettingsRepliesRoute
  '/$workspaceSlug/settings/rss': typeof DashboardWorkspaceSlugSettingsRssRoute
  '/$workspaceSlug/settings/schedule': typeof DashboardWorkspaceSlugSettingsScheduleRoute
  '/$workspaceSlug/settings/security': typeof DashboardWorkspaceSlugSettingsSecurityRoute
  '/$workspaceSlug/settings/white-label': typeof DashboardWorkspaceSlugSettingsWhiteLabelRoute
  '/$workspaceSlug/templates/series': typeof DashboardWorkspaceSlugTemplatesSeriesRoute
  '/api/admin/queues/$': typeof ApiAdminQueuesSplatRoute
  '/api/admin/users/export': typeof ApiAdminUsersExportRoute
  '/api/billing/webhook/$provider': typeof ApiBillingWebhookProviderRoute
  '/api/calendar/$token/ics': typeof ApiCalendarTokenIcsRoute
  '/api/oauth/callback/$platform': typeof ApiOauthCallbackPlatformRoute
  '/api/v1/campaigns/$id': typeof ApiV1CampaignsIdRoute
  '/api/v1/media/$id': typeof ApiV1MediaIdRoute
  '/api/v1/openapi/json': typeof ApiV1OpenapiJsonRoute
  '/api/v1/posts/$id': typeof ApiV1PostsIdRoute
  '/$workspaceSlug/posts': typeof DashboardWorkspaceSlugPostsIndexRoute
  '/$workspaceSlug/settings': typeof DashboardWorkspaceSlugSettingsIndexRoute
  '/api/admin/queues': typeof ApiAdminQueuesIndexRoute
  '/$workspaceSlug/posts/campaigns/$campaignId': typeof DashboardWorkspaceSlugPostsCampaignsCampaignIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/admin': typeof AdminRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/onboarding': typeof OnboardingRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_dashboard/$workspaceSlug': typeof DashboardWorkspaceSlugRouteWithChildren
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/logins': typeof AdminLoginsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/bio/$handle': typeof BioHandleRoute
  '/c/$token': typeof CTokenRoute
  '/digest/unsubscribe': typeof DigestUnsubscribeRoute
  '/l/$slug': typeof LSlugRoute
  '/review/$token': typeof ReviewTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/_dashboard/$workspaceSlug/accounts': typeof DashboardWorkspaceSlugAccountsRoute
  '/_dashboard/$workspaceSlug/activity': typeof DashboardWorkspaceSlugActivityRoute
  '/_dashboard/$workspaceSlug/analytics': typeof DashboardWorkspaceSlugAnalyticsRoute
  '/_dashboard/$workspaceSlug/approvals': typeof DashboardWorkspaceSlugApprovalsRoute
  '/_dashboard/$workspaceSlug/calendar': typeof DashboardWorkspaceSlugCalendarRoute
  '/_dashboard/$workspaceSlug/compose': typeof DashboardWorkspaceSlugComposeRoute
  '/_dashboard/$workspaceSlug/inbox': typeof DashboardWorkspaceSlugInboxRoute
  '/_dashboard/$workspaceSlug/media': typeof DashboardWorkspaceSlugMediaRoute
  '/_dashboard/$workspaceSlug/monitors': typeof DashboardWorkspaceSlugMonitorsRoute
  '/_dashboard/$workspaceSlug/notifications': typeof DashboardWorkspaceSlugNotificationsRoute
  '/_dashboard/$workspaceSlug/team': typeof DashboardWorkspaceSlugTeamRoute
  '/_dashboard/$workspaceSlug/templates': typeof DashboardWorkspaceSlugTemplatesRouteWithChildren
  '/admin/workspaces/$workspaceId': typeof AdminWorkspacesWorkspaceIdRoute
  '/api/account/export': typeof ApiAccountExportRoute
  '/api/activity/export': typeof ApiActivityExportRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/ai/hashtags': typeof ApiAiHashtagsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/notifications/unread-count': typeof ApiNotificationsUnreadCountRoute
  '/api/posts/export': typeof ApiPostsExportRoute
  '/api/reports/analytics': typeof ApiReportsAnalyticsRoute
  '/api/v1/accounts': typeof ApiV1AccountsRoute
  '/api/v1/analytics': typeof ApiV1AnalyticsRoute
  '/api/v1/campaigns': typeof ApiV1CampaignsRouteWithChildren
  '/api/v1/media': typeof ApiV1MediaRouteWithChildren
  '/api/v1/posts': typeof ApiV1PostsRouteWithChildren
  '/_dashboard/$workspaceSlug/': typeof DashboardWorkspaceSlugIndexRoute
  '/admin/workspaces/': typeof AdminWorkspacesIndexRoute
  '/_dashboard/$workspaceSlug/settings/ai': typeof DashboardWorkspaceSlugSettingsAiRoute
  '/_dashboard/$workspaceSlug/settings/api': typeof DashboardWorkspaceSlugSettingsApiRoute
  '/_dashboard/$workspaceSlug/settings/billing': typeof DashboardWorkspaceSlugSettingsBillingRoute
  '/_dashboard/$workspaceSlug/settings/bio': typeof DashboardWorkspaceSlugSettingsBioRoute
  '/_dashboard/$workspaceSlug/settings/notifications': typeof DashboardWorkspaceSlugSettingsNotificationsRoute
  '/_dashboard/$workspaceSlug/settings/replies': typeof DashboardWorkspaceSlugSettingsRepliesRoute
  '/_dashboard/$workspaceSlug/settings/rss': typeof DashboardWorkspaceSlugSettingsRssRoute
  '/_dashboard/$workspaceSlug/settings/schedule': typeof DashboardWorkspaceSlugSettingsScheduleRoute
  '/_dashboard/$workspaceSlug/settings/security': typeof DashboardWorkspaceSlugSettingsSecurityRoute
  '/_dashboard/$workspaceSlug/settings/white-label': typeof DashboardWorkspaceSlugSettingsWhiteLabelRoute
  '/_dashboard/$workspaceSlug/templates/series': typeof DashboardWorkspaceSlugTemplatesSeriesRoute
  '/api/admin/queues/$': typeof ApiAdminQueuesSplatRoute
  '/api/admin/users/export': typeof ApiAdminUsersExportRoute
  '/api/billing/webhook/$provider': typeof ApiBillingWebhookProviderRoute
  '/api/calendar/$token/ics': typeof ApiCalendarTokenIcsRoute
  '/api/oauth/callback/$platform': typeof ApiOauthCallbackPlatformRoute
  '/api/v1/campaigns/$id': typeof ApiV1CampaignsIdRoute
  '/api/v1/media/$id': typeof ApiV1MediaIdRoute
  '/api/v1/openapi/json': typeof ApiV1OpenapiJsonRoute
  '/api/v1/posts/$id': typeof ApiV1PostsIdRoute
  '/_dashboard/$workspaceSlug/posts/': typeof DashboardWorkspaceSlugPostsIndexRoute
  '/_dashboard/$workspaceSlug/settings/': typeof DashboardWorkspaceSlugSettingsIndexRoute
  '/api/admin/queues/': typeof ApiAdminQueuesIndexRoute
  '/_dashboard/$workspaceSlug/posts/campaigns/$campaignId': typeof DashboardWorkspaceSlugPostsCampaignsCampaignIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/admin'
    | '/healthz'
    | '/onboarding'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/$workspaceSlug'
    | '/admin/api-keys'
    | '/admin/audit'
    | '/admin/jobs'
    | '/admin/logins'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/webhooks'
    | '/bio/$handle'
    | '/c/$token'
    | '/digest/unsubscribe'
    | '/l/$slug'
    | '/review/$token'
    | '/admin/'
    | '/$workspaceSlug/accounts'
    | '/$workspaceSlug/activity'
    | '/$workspaceSlug/analytics'
    | '/$workspaceSlug/approvals'
    | '/$workspaceSlug/calendar'
    | '/$workspaceSlug/compose'
    | '/$workspaceSlug/inbox'
    | '/$workspaceSlug/media'
    | '/$workspaceSlug/monitors'
    | '/$workspaceSlug/notifications'
    | '/$workspaceSlug/team'
    | '/$workspaceSlug/templates'
    | '/admin/workspaces/$workspaceId'
    | '/api/account/export'
    | '/api/activity/export'
    | '/api/ai/generate'
    | '/api/ai/hashtags'
    | '/api/auth/$'
    | '/api/media/upload'
    | '/api/notifications/unread-count'
    | '/api/posts/export'
    | '/api/reports/analytics'
    | '/api/v1/accounts'
    | '/api/v1/analytics'
    | '/api/v1/campaigns'
    | '/api/v1/media'
    | '/api/v1/posts'
    | '/$workspaceSlug/'
    | '/admin/workspaces/'
    | '/$workspaceSlug/settings/ai'
    | '/$workspaceSlug/settings/api'
    | '/$workspaceSlug/settings/billing'
    | '/$workspaceSlug/settings/bio'
    | '/$workspaceSlug/settings/notifications'
    | '/$workspaceSlug/settings/replies'
    | '/$workspaceSlug/settings/rss'
    | '/$workspaceSlug/settings/schedule'
    | '/$workspaceSlug/settings/security'
    | '/$workspaceSlug/settings/white-label'
    | '/$workspaceSlug/templates/series'
    | '/api/admin/queues/$'
    | '/api/admin/users/export'
    | '/api/billing/webhook/$provider'
    | '/api/calendar/$token/ics'
    | '/api/oauth/callback/$platform'
    | '/api/v1/campaigns/$id'
    | '/api/v1/media/$id'
    | '/api/v1/openapi/json'
    | '/api/v1/posts/$id'
    | '/$workspaceSlug/posts/'
    | '/$workspaceSlug/settings/'
    | '/api/admin/queues/'
    | '/$workspaceSlug/posts/campaigns/$campaignId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/healthz'
    | '/onboarding'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/admin/api-keys'
    | '/admin/audit'
    | '/admin/jobs'
    | '/admin/logins'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/webhooks'
    | '/bio/$handle'
    | '/c/$token'
    | '/digest/unsubscribe'
    | '/l/$slug'
    | '/review/$token'
    | '/admin'
    | '/$workspaceSlug/accounts'
    | '/$workspaceSlug/activity'
    | '/$workspaceSlug/analytics'
    | '/$workspaceSlug/approvals'
    | '/$workspaceSlug/calendar'
    | '/$workspaceSlug/compose'
    | '/$workspaceSlug/inbox'
    | '/$workspaceSlug/media'
    | '/$workspaceSlug/monitors'
    | '/$workspaceSlug/notifications'
    | '/$workspaceSlug/team'
    | '/$workspaceSlug/templates'
    | '/admin/workspaces/$workspaceId'
    | '/api/account/export'
    | '/api/activity/export'
    | '/api/ai/generate'
    | '/api/ai/hashtags'
    | '/api/auth/$'
    | '/api/media/upload'
    | '/api/notifications/unread-count'
    | '/api/posts/export'
    | '/api/reports/analytics'
    | '/api/v1/accounts'
    | '/api/v1/analytics'
    | '/api/v1/campaigns'
    | '/api/v1/media'
    | '/api/v1/posts'
    | '/$workspaceSlug'
    | '/admin/workspaces'
    | '/$workspaceSlug/settings/ai'
    | '/$workspaceSlug/settings/api'
    | '/$workspaceSlug/settings/billing'
    | '/$workspaceSlug/settings/bio'
    | '/$workspaceSlug/settings/notifications'
    | '/$workspaceSlug/settings/replies'
    | '/$workspaceSlug/settings/rss'
    | '/$workspaceSlug/settings/schedule'
    | '/$workspaceSlug/settings/security'
    | '/$workspaceSlug/settings/white-label'
    | '/$workspaceSlug/templates/series'
    | '/api/admin/queues/$'
    | '/api/admin/users/export'
    | '/api/billing/webhook/$provider'
    | '/api/calendar/$token/ics'
    | '/api/oauth/callback/$platform'
    | '/api/v1/campaigns/$id'
    | '/api/v1/media/$id'
    | '/api/v1/openapi/json'
    | '/api/v1/posts/$id'
    | '/$workspaceSlug/posts'
    | '/$workspaceSlug/settings'
    | '/api/admin/queues'
    | '/$workspaceSlug/posts/campaigns/$campaignId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_dashboard'
    | '/accept-invitation'
    | '/admin'
    | '/healthz'
    | '/onboarding'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/verify-email'
    | '/_dashboard/$workspaceSlug'
    | '/admin/api-keys'
    | '/admin/audit'
    | '/admin/jobs'
    | '/admin/logins'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/webhooks'
    | '/bio/$handle'
    | '/c/$token'
    | '/digest/unsubscribe'
    | '/l/$slug'
    | '/review/$token'
    | '/admin/'
    | '/_dashboard/$workspaceSlug/accounts'
    | '/_dashboard/$workspaceSlug/activity'
    | '/_dashboard/$workspaceSlug/analytics'
    | '/_dashboard/$workspaceSlug/approvals'
    | '/_dashboard/$workspaceSlug/calendar'
    | '/_dashboard/$workspaceSlug/compose'
    | '/_dashboard/$workspaceSlug/inbox'
    | '/_dashboard/$workspaceSlug/media'
    | '/_dashboard/$workspaceSlug/monitors'
    | '/_dashboard/$workspaceSlug/notifications'
    | '/_dashboard/$workspaceSlug/team'
    | '/_dashboard/$workspaceSlug/templates'
    | '/admin/workspaces/$workspaceId'
    | '/api/account/export'
    | '/api/activity/export'
    | '/api/ai/generate'
    | '/api/ai/hashtags'
    | '/api/auth/$'
    | '/api/media/upload'
    | '/api/notifications/unread-count'
    | '/api/posts/export'
    | '/api/reports/analytics'
    | '/api/v1/accounts'
    | '/api/v1/analytics'
    | '/api/v1/campaigns'
    | '/api/v1/media'
    | '/api/v1/posts'
    | '/_dashboard/$workspaceSlug/'
    | '/admin/workspaces/'
    | '/_dashboard/$workspaceSlug/settings/ai'
    | '/_dashboard/$workspaceSlug/settings/api'
    | '/_dashboard/$workspaceSlug/settings/billing'
    | '/_dashboard/$workspaceSlug/settings/bio'
    | '/_dashboard/$workspaceSlug/settings/notifications'
    | '/_dashboard/$workspaceSlug/settings/replies'
    | '/_dashboard/$workspaceSlug/settings/rss'
    | '/_dashboard/$workspaceSlug/settings/schedule'
    | '/_dashboard/$workspaceSlug/settings/security'
    | '/_dashboard/$workspaceSlug/settings/white-label'
    | '/_dashboard/$workspaceSlug/templates/series'
    | '/api/admin/queues/$'
    | '/api/admin/users/export'
    | '/api/billing/webhook/$provider'
    | '/api/calendar/$token/ics'
    | '/api/oauth/callback/$platform'
    | '/api/v1/campaigns/$id'
    | '/api/v1/media/$id'
    | '/api/v1/openapi/json'
    | '/api/v1/posts/$id'
    | '/_dashboard/$workspaceSlug/posts/'
    | '/_dashboard/$workspaceSlug/settings/'
    | '/api/admin/queues/'
    | '/_dashboard/$workspaceSlug/posts/campaigns/$campaignId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  AdminRoute: typeof AdminRouteWithChildren
  HealthzRoute: typeof HealthzRoute
  OnboardingRoute: typeof OnboardingRoute
  BioHandleRoute: typeof BioHandleRoute
  CTokenRoute: typeof CTokenRoute
  DigestUnsubscribeRoute: typeof DigestUnsubscribeRoute
  LSlugRoute: typeof LSlugRoute
  ReviewTokenRoute: typeof ReviewTokenRoute
  ApiAccountExportRoute: typeof ApiAccountExportRoute
  ApiActivityExportRoute: typeof ApiActivityExportRoute
  ApiAiGenerateRoute: typeof ApiAiGenerateRoute
  ApiAiHashtagsRoute: typeof ApiAiHashtagsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMediaUploadRoute: typeof ApiMediaUploadRoute
  ApiNotificationsUnreadCountRoute: typeof ApiNotificationsUnreadCountRoute
  ApiPostsExportRoute: typeof ApiPostsExportRoute
  ApiReportsAnalyticsRoute: typeof ApiReportsAnalyticsRoute
  ApiV1AccountsRoute: typeof ApiV1AccountsRoute
  ApiV1AnalyticsRoute: typeof ApiV1AnalyticsRoute
  ApiV1CampaignsRoute: typeof ApiV1CampaignsRouteWithChildren
  ApiV1MediaRoute: typeof ApiV1MediaRouteWithChildren
  ApiV1PostsRoute: typeof ApiV1PostsRouteWithChildren
  ApiAdminQueuesSplatRoute: typeof ApiAdminQueuesSplatRoute
  ApiAdminUsersExportRoute: typeof ApiAdminUsersExportRoute
  ApiBillingWebhookProviderRoute: typeof ApiBillingWebhookProviderRoute
  ApiCalendarTokenIcsRoute: typeof ApiCalendarTokenIcsRoute
  ApiOauthCallbackPlatformRoute: typeof ApiOauthCallbackPlatformRoute
  ApiV1OpenapiJsonRoute: typeof ApiV1OpenapiJsonRoute
  ApiAdminQueuesIndexRoute: typeof ApiAdminQueuesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/review/$token': {
      id: '/review/$token'
      path: '/review/$token'
      fullPath: '/review/$token'
      preLoaderRoute: typeof ReviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l/$slug': {
      id: '/l/$slug'
      path: '/l/$slug'
      fullPath: '/l/$slug'
      preLoaderRoute: typeof LSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digest/unsubscribe': {
      id: '/digest/unsubscribe'
      path: '/digest/unsubscribe'
      fullPath: '/digest/unsubscribe'
      preLoaderRoute: typeof DigestUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bio/$handle': {
      id: '/bio/$handle'
      path: '/bio/$handle'
      fullPath: '/bio/$handle'
      preLoaderRoute: typeof BioHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/webhooks': {
      id: '/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AdminWebhooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logins': {
      id: '/admin/logins'
      path: '/logins'
      fullPath: '/admin/logins'
      preLoaderRoute: typeof AdminLoginsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-keys': {
      id: '/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AdminApiKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_dashboard/$workspaceSlug': {
      id: '/_dashboard/$workspaceSlug'
      path: '/$workspaceSlug'
      fullPath: '/$workspaceSlug'
      preLoaderRoute: typeof DashboardWorkspaceSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/workspaces/': {
      id: '/admin/workspaces/'
      path: '/workspaces'
      fullPath: '/admin/workspaces/'
      preLoaderRoute: typeof AdminWorkspacesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_dashboard/$workspaceSlug/': {
      id: '/_dashboard/$workspaceSlug/'
      path: '/'
      fullPath: '/$workspaceSlug/'
      preLoaderRoute: typeof DashboardWorkspaceSlugIndexRouteImport
      parentRoute: typeof DashboardWorkspaceSlugRoute
    }
    '/api/v1/posts': {
      id: '/api/v1/posts'
      path: '/api/v1/posts'
      fullPath: '/api/v1/posts'
      preLoaderRoute: typeof ApiV1PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/media': {
      id: '/api/v1/media'
      path: '/api/v1/media'
      fullPath: '/api/v1/media'
      preLoaderRoute: typeof ApiV1MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/campaigns': {
      id: '/api/v1/campaigns'
      path: '/api/v1/campaigns'
      fullPath: '/api/v1/campaigns'
      preLoaderRoute: typeof ApiV1CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/analytics': {
      id: '/api/v1/analytics'
      path: '/api/v1/analytics'
      fullPath: '/api/v1/analytics'
      preLoaderRoute: typeof ApiV1AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/accounts': {
      id: '/api/v1/accounts'
      path: '/api/v1/accounts'
      fullPath: '/api/v1/accounts'
      preLoaderRoute: typeof ApiV1AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/analytics': {
      id: '/api/reports/analytics'
      path: '/api/reports/analytics'
      fullPath: '/api/reports/analytics'
      preLoaderRoute: typeof ApiReportsAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts/export': {
      id: '/api/posts/export'
      path: '/api/posts/export'
      fullPath: '/api/posts/export'
      preLoaderRoute: typeof ApiPostsExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/unread-count': {
      id: '/api/notifications/unread-count'
      path: '/api/notifications/unread-count'
      fullPath: '/api/notifications/unread-count'
      preLoaderRoute: typeof ApiNotificationsUnreadCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/upload': {
      id: '/api/media/upload'
      path: '/api/media/upload'
      fullPath: '/api/media/upload'
      preLoaderRoute: typeof ApiMediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/hashtags': {
      id: '/api/ai/hashtags'
      path: '/api/ai/hashtags'
      fullPath: '/api/ai/hashtags'
      preLoaderRoute: typeof ApiAiHashtagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate': {
      id: '/api/ai/generate'
      path: '/api/ai/generate'
      fullPath: '/api/ai/generate'
      preLoaderRoute: typeof ApiAiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/activity/export': {
      id: '/api/activity/export'
      path: '/api/activity/export'
      fullPath: '/api/activity/export'
      preLoaderRoute: typeof ApiActivityExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/export': {
      id: '/api/account/export'
      path: '/api/account/export'
      fullPath: '/api/account/export'
      preLoaderRoute: typeof ApiAccountExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workspaces/$workspaceId': {
      id: '/admin/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/admin/workspaces/$workspaceId'
      preLoaderRoute: typeof AdminWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_dashboard/$workspaceSlug/templates': {
      id: '/_dashboard/$workspaceSlug/templates'
      path: '/templates'
      fullPath: '/$workspaceSlug/templates'
      preLoaderRoute: typeof DashboardWorkspaceSlugTemplatesRouteImport
      parentRoute: typeof DashboardWorkspaceSlugRoute
    }
    '/_dashboard/$workspaceSlug/team': {
      id: '/_dashboard/$workspaceSlug/team'
      path: '/team'
      fullPath: '/$workspaceSlug/team'
      preLoaderRoute: typeof DashboardWorkspaceSlugTeamRouteImport
      parentRoute: typeof DashboardWorkspaceSlugRoute
    }
    '/_dashboard/$workspaceSlug/notifications': {
      id: '/_dashboard/$workspaceSlug/notifications'
      path: '/notifications'
      fullPath: '/$workspaceSlug/notifications'
      preLoaderRoute: typeof DashboardWorkspaceSlugNotificationsRouteImport
      parentRoute: typeof DashboardWorkspaceSlugRoute
    }
    '/_dashboard/$workspaceSlug/monitors': {
      id: '/_dashboard/$workspaceSlug/monitors'
      path: '/monitors'
      fullPath: '/$workspaceSlug/monitors'
      preLoaderRoute: typeof DashboardWorkspaceSlugMonitorsRouteImport
      parentRoute: typeof DashboardWorkspaceSlugRoute
    }
    '/_dashboard/$workspaceSlug/media': {
      id: '/_dashboard/$workspaceSlug/media'
      path: '/media'
      fullPath: '/$workspaceSlug/media'
      preLoaderRoute: typeof DashboardWorkspaceSlugMediaRouteImport
      parentRoute: typeof DashboardWorkspaceSlugRoute
    }
    '/_dashboard/$workspaceSlug/inbox': {
      id: '/_dashboard/$workspaceSlug/inbox'
      path: '/inbox'
      fullPath: '/$workspaceSlug/inbox'
      preLoaderRoute: typeof DashboardWorkspaceSlugInboxRouteImport
      parentRoute: typeof DashboardWorkspaceSlugRoute
    }
    '/_dashboard/$workspaceSlug/compose': {
      id: '/_dashboard/$workspaceSlug/compose'
      path: '/compose'
      fullPath: '/$workspaceSlug/compose'
      preLoaderRoute: typeof DashboardWorkspaceSlugComposeRouteImport
      parentRoute: typeof DashboardWorkspaceSlugRoute
    }
    '/_dashboard/$workspaceSlug/calendar': {
      id: '/_dashboard/$workspaceSlug/calendar'
      path: '/calendar'
      fullPath: '/$workspaceSlug/calendar'
      preLoaderRoute: typeof DashboardWorkspaceSlugCalendarRouteImport
      parentRoute: typeof DashboardWorkspaceSlugRoute
    }
    '/_dashboard/$workspaceSlug/approvals': {
      id: '/_dashboard/$workspaceSlug/approvals'
      path: '/approvals'
      fullPath: '/$workspaceSlug/approvals'
      preLoaderRoute: typeof DashboardWorkspaceSlugApprovalsRouteImport
      parentRoute: typeof DashboardWorkspaceSlugRoute
    }
    '/_dashboard/$workspaceSlug/analytics': {
      id: '/_dashboard/$workspaceSlug/analytics'
      path: '/analytics'
      fullPath: '/$workspaceSlug/analytics'
      preLoaderRoute: typeof DashboardWorkspaceSlugAnalyticsRouteImport
      parentRoute: typeof DashboardWorkspaceSlugRoute
    }
    '/_dashboard/$workspaceSlug/activity': {
      id: '/_dashboard/$workspaceSlug/activity'
      path: '/activity'
      fullPath: '/$workspaceSlug/activity'
      preLoaderRoute: typeof DashboardWorkspaceSlugActivityRouteImport
      parentRoute: typeof DashboardWorkspaceSlugRoute
    }
    '/_dashboard/$workspaceSlug/accounts': {
      id: '/_dashboard/$workspaceSlug/accounts'
      path: '/accounts'
      fullPath: '/$workspaceSlug/accounts'
      preLoaderRoute: typeof DashboardWorkspaceSlugAccountsRouteImport
      parentRoute: typeof DashboardWorkspaceSlugRoute
    }
    '/api/admin/queues/': {
      id: '/api/admin/queues/'
      path: '/api/admin/queues'
      fullPath: '/api/admin/queues/'
      preLoaderRoute: typeof ApiAdminQueuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/$workspaceSlug/settings/': {
      id: '/_dashboard/$workspaceSlug/settings/'
      path: '/settings'
      fullPath: '/$workspaceSlug/settings/'
      preLoaderRoute: typeof DashboardWorkspaceSlugSettingsIndexRouteImport
      parentRoute: typeof DashboardWorkspaceSlugRoute
    }
    '/_dashboard/$workspaceSlug/posts/': {
      id: '/_dashboard/$workspaceSlug/posts/'
      path: '/posts'
      fullPath: '/$workspaceSlug/posts/'
      preLoaderRoute: typeof DashboardWorkspaceSlugPostsIndexRouteImport
      parentRoute: typeof DashboardWorkspaceSlugRoute
    }
    '/api/v1/posts/$id': {
      id: '/api/v1/posts/$id'
      path: '/$id'
      fullPath: '/api/v1/posts/$id'
      preLoaderRoute: typeof ApiV1PostsIdRouteImport
      parentRoute: typeof ApiV1PostsRoute
    }
    '/api/v1/openapi/json': {
      id: '/api/v1/openapi/json'
      path: '/api/v1/openapi/json'
      fullPath: '/api/v1/openapi/json'
      preLoaderRoute: typeof ApiV1OpenapiJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/media/$id': {
      id: '/api/v1/media/$id'
      path: '/$id'
      fullPath: '/api/v1/media/$id'
      preLoaderRoute: typeof ApiV1MediaIdRouteImport
      parentRoute: typeof ApiV1MediaRoute
    }
    '/api/v1/campaigns/$id': {
      id: '/api/v1/campaigns/$id'
      path: '/$id'
      fullPath: '/api/v1/campaigns/$id'
      preLoaderRoute: typeof ApiV1CampaignsIdRouteImport
      parentRoute: typeof ApiV1CampaignsRoute
    }
    '/api/oauth/callback/$platform': {
      id: '/api/oauth/callback/$platform'
      path: '/api/oauth/callback/$platform'
      fullPath: '/api/oauth/callback/$platform'
      preLoaderRoute: typeof ApiOauthCallbackPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/$token/ics': {
      id: '/api/calendar/$token/ics'
      path: '/api/calendar/$token/ics'
      fullPath: '/api/calendar/$token/ics'
      preLoaderRoute: typeof ApiCalendarTokenIcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook/$provider': {
      id: '/api/billing/webhook/$provider'
      path: '/api/billing/webhook/$provider'
      fullPath: '/api/billing/webhook/$provider'
      preLoaderRoute: typeof ApiBillingWebhookProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/export': {
      id: '/api/admin/users/export'
      path: '/api/admin/users/export'
      fullPath: '/api/admin/users/export'
      preLoaderRoute: typeof ApiAdminUsersExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/queues/$': {
      id: '/api/admin/queues/$'
      path: '/api/admin/queues/$'
      fullPath: '/api/admin/queues/$'
      preLoaderRoute: typeof ApiAdminQueuesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/$workspaceSlug/templates/series': {
      id: '/_dashboard/$workspaceSlug/templates/series'
      path: '/series'
      fullPath: '/$workspaceSlug/templates/series'
      preLoaderRoute: typeof DashboardWorkspaceSlugTemplatesSeriesRouteImport
      parentRoute: typeof DashboardWorkspaceSlugTemplatesRoute
    }
    '/_dashboard/$workspaceSlug/settings/white-label': {
      id: '/_dashboard/$workspaceSlug/settings/white-label'
      path: '/settings/white-label'
      fullPath: '/$workspaceSlug/settings/white-label'
      preLoaderRoute: typeof DashboardWorkspaceSlugSettingsWhiteLabelRouteImport
      parentRoute: typeof DashboardWorkspaceSlugRoute
    }
    '/_dashboard/$workspaceSlug/settings/security': {
      id: '/_dashboard/$workspaceSlug/settings/security'
      path: '/settings/security'
      fullPath: '/$workspaceSlug/settings/security'
      preLoaderRoute: typeof DashboardWorkspaceSlugSettingsSecurityRouteImport
      parentRoute: typeof DashboardWorkspaceSlugRoute
    }
    '/_dashboard/$workspaceSlug/settings/schedule': {
      id: '/_dashboard/$workspaceSlug/settings/schedule'
      path: '/settings/schedule'
      fullPath: '/$workspaceSlug/settings/schedule'
      preLoaderRoute: typeof DashboardWorkspaceSlugSettingsScheduleRouteImport
      parentRoute: typeof DashboardWorkspaceSlugRoute
    }
    '/_dashboard/$workspaceSlug/settings/rss': {
      id: '/_dashboard/$workspaceSlug/settings/rss'
      path: '/settings/rss'
      fullPath: '/$workspaceSlug/settings/rss'
      preLoaderRoute: typeof DashboardWorkspaceSlugSettingsRssRouteImport
      parentRoute: typeof DashboardWorkspaceSlugRoute
    }
    '/_dashboard/$workspaceSlug/settings/replies': {
      id: '/_dashboard/$workspaceSlug/settings/replies'
      path: '/settings/replies'
      fullPath: '/$workspaceSlug/settings/replies'
      preLoaderRoute: typeof DashboardWorkspaceSlugSettingsRepliesRouteImport
      parentRoute: typeof DashboardWorkspaceSlugRoute
    }
    '/_dashboard/$workspaceSlug/settings/notifications': {
      id: '/_dashboard/$workspaceSlug/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/$workspaceSlug/settings/notifications'
      preLoaderRoute: typeof DashboardWorkspaceSlugSettingsNotificationsRouteImport
      parentRoute: typeof DashboardWorkspaceSlugRoute
    }
    '/_dashboard/$workspaceSlug/settings/bio': {
      id: '/_dashboard/$workspaceSlug/settings/bio'
      path: '/settings/bio'
      fullPath: '/$workspaceSlug/settings/bio'
      preLoaderRoute: typeof DashboardWorkspaceSlugSettingsBioRouteImport
      parentRoute: typeof DashboardWorkspaceSlugRoute
    }
    '/_dashboard/$workspaceSlug/settings/billing': {
      id: '/_dashboard/$workspaceSlug/settings/billing'
      path: '/settings/billing'
      fullPath: '/$workspaceSlug/settings/billing'
      preLoaderRoute: typeof DashboardWorkspaceSlugSettingsBillingRouteImport
      parentRoute: typeof DashboardWorkspaceSlugRoute
    }
    '/_dashboard/$workspaceSlug/settings/api': {
      id: '/_dashboard/$workspaceSlug/settings/api'
      path: '/settings/api'
      fullPath: '/$workspaceSlug/settings/api'
      preLoaderRoute: typeof DashboardWorkspaceSlugSettingsApiRouteImport
      parentRoute: typeof DashboardWorkspaceSlugRoute
    }
    '/_dashboard/$workspaceSlug/settings/ai': {
      id: '/_dashboard/$workspaceSlug/settings/ai'
      path: '/settings/ai'
      fullPath: '/$workspaceSlug/settings/ai'
      preLoaderRoute: typeof DashboardWorkspaceSlugSettingsAiRouteImport
      parentRoute: typeof DashboardWorkspaceSlugRoute
    }
    '/_dashboard/$workspaceSlug/posts/campaigns/$campaignId': {
      id: '/_dashboard/$workspaceSlug/posts/campaigns/$campaignId'
      path: '/posts/campaigns/$campaignId'
      fullPath: '/$workspaceSlug/posts/campaigns/$campaignId'
      preLoaderRoute: typeof DashboardWorkspaceSlugPostsCampaignsCampaignIdRouteImport
      parentRoute: typeof DashboardWorkspaceSlugRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardWorkspaceSlugTemplatesRouteChildren {
  DashboardWorkspaceSlugTemplatesSeriesRoute: typeof DashboardWorkspaceSlugTemplatesSeriesRoute
}

const DashboardWorkspaceSlugTemplatesRouteChildren: DashboardWorkspaceSlugTemplatesRouteChildren =
  {
    DashboardWorkspaceSlugTemplatesSeriesRoute:
      DashboardWorkspaceSlugTemplatesSeriesRoute,
  }

const DashboardWorkspaceSlugTemplatesRouteWithChildren =
  DashboardWorkspaceSlugTemplatesRoute._addFileChildren(
    DashboardWorkspaceSlugTemplatesRouteChildren,
  )

interface DashboardWorkspaceSlugRouteChildren {
  DashboardWorkspaceSlugAccountsRoute: typeof DashboardWorkspaceSlugAccountsRoute
  DashboardWorkspaceSlugActivityRoute: typeof DashboardWorkspaceSlugActivityRoute
  DashboardWorkspaceSlugAnalyticsRoute: typeof DashboardWorkspaceSlugAnalyticsRoute
  DashboardWorkspaceSlugApprovalsRoute: typeof DashboardWorkspaceSlugApprovalsRoute
  DashboardWorkspaceSlugCalendarRoute: typeof DashboardWorkspaceSlugCalendarRoute
  DashboardWorkspaceSlugComposeRoute: typeof DashboardWorkspaceSlugComposeRoute
  DashboardWorkspaceSlugInboxRoute: typeof DashboardWorkspaceSlugInboxRoute
  DashboardWorkspaceSlugMediaRoute: typeof DashboardWorkspaceSlugMediaRoute
  DashboardWorkspaceSlugMonitorsRoute: typeof DashboardWorkspaceSlugMonitorsRoute
  DashboardWorkspaceSlugNotificationsRoute: typeof DashboardWorkspaceSlugNotificationsRoute
  DashboardWorkspaceSlugTeamRoute: typeof DashboardWorkspaceSlugTeamRoute
  DashboardWorkspaceSlugTemplatesRoute: typeof DashboardWorkspaceSlugTemplatesRouteWithChildren
  DashboardWorkspaceSlugIndexRoute: typeof DashboardWorkspaceSlugIndexRoute
  DashboardWorkspaceSlugSettingsAiRoute: typeof DashboardWorkspaceSlugSettingsAiRoute
  DashboardWorkspaceSlugSettingsApiRoute: typeof DashboardWorkspaceSlugSettingsApiRoute
  DashboardWorkspaceSlugSettingsBillingRoute: typeof DashboardWorkspaceSlugSettingsBillingRoute
  DashboardWorkspaceSlugSettingsBioRoute: typeof DashboardWorkspaceSlugSettingsBioRoute
  DashboardWorkspaceSlugSettingsNotificationsRoute: typeof DashboardWorkspaceSlugSettingsNotificationsRoute
  DashboardWorkspaceSlugSettingsRepliesRoute: typeof DashboardWorkspaceSlugSettingsRepliesRoute
  DashboardWorkspaceSlugSettingsRssRoute: typeof DashboardWorkspaceSlugSettingsRssRoute
  DashboardWorkspaceSlugSettingsScheduleRoute: typeof DashboardWorkspaceSlugSettingsScheduleRoute
  DashboardWorkspaceSlugSettingsSecurityRoute: typeof DashboardWorkspaceSlugSettingsSecurityRoute
  DashboardWorkspaceSlugSettingsWhiteLabelRoute: typeof DashboardWorkspaceSlugSettingsWhiteLabelRoute
  DashboardWorkspaceSlugPostsIndexRoute: typeof DashboardWorkspaceSlugPostsIndexRoute
  DashboardWorkspaceSlugSettingsIndexRoute: typeof DashboardWorkspaceSlugSettingsIndexRoute
  DashboardWorkspaceSlugPostsCampaignsCampaignIdRoute: typeof DashboardWorkspaceSlugPostsCampaignsCampaignIdRoute
}

const DashboardWorkspaceSlugRouteChildren: DashboardWorkspaceSlugRouteChildren =
  {
    DashboardWorkspaceSlugAccountsRoute: DashboardWorkspaceSlugAccountsRoute,
    DashboardWorkspaceSlugActivityRoute: DashboardWorkspaceSlugActivityRoute,
    DashboardWorkspaceSlugAnalyticsRoute: DashboardWorkspaceSlugAnalyticsRoute,
    DashboardWorkspaceSlugApprovalsRoute: DashboardWorkspaceSlugApprovalsRoute,
    DashboardWorkspaceSlugCalendarRoute: DashboardWorkspaceSlugCalendarRoute,
    DashboardWorkspaceSlugComposeRoute: DashboardWorkspaceSlugComposeRoute,
    DashboardWorkspaceSlugInboxRoute: DashboardWorkspaceSlugInboxRoute,
    DashboardWorkspaceSlugMediaRoute: DashboardWorkspaceSlugMediaRoute,
    DashboardWorkspaceSlugMonitorsRoute: DashboardWorkspaceSlugMonitorsRoute,
    DashboardWorkspaceSlugNotificationsRoute:
      DashboardWorkspaceSlugNotificationsRoute,
    DashboardWorkspaceSlugTeamRoute: DashboardWorkspaceSlugTeamRoute,
    DashboardWorkspaceSlugTemplatesRoute:
      DashboardWorkspaceSlugTemplatesRouteWithChildren,
    DashboardWorkspaceSlugIndexRoute: DashboardWorkspaceSlugIndexRoute,
    DashboardWorkspaceSlugSettingsAiRoute:
      DashboardWorkspaceSlugSettingsAiRoute,
    DashboardWorkspaceSlugSettingsApiRoute:
      DashboardWorkspaceSlugSettingsApiRoute,
    DashboardWorkspaceSlugSettingsBillingRoute:
      DashboardWorkspaceSlugSettingsBillingRoute,
    DashboardWorkspaceSlugSettingsBioRoute:
      DashboardWorkspaceSlugSettingsBioRoute,
    DashboardWorkspaceSlugSettingsNotificationsRoute:
      DashboardWorkspaceSlugSettingsNotificationsRoute,
    DashboardWorkspaceSlugSettingsRepliesRoute:
      DashboardWorkspaceSlugSettingsRepliesRoute,
    DashboardWorkspaceSlugSettingsRssRoute:
      DashboardWorkspaceSlugSettingsRssRoute,
    DashboardWorkspaceSlugSettingsScheduleRoute:
      DashboardWorkspaceSlugSettingsScheduleRoute,
    DashboardWorkspaceSlugSettingsSecurityRoute:
      DashboardWorkspaceSlugSettingsSecurityRoute,
    DashboardWorkspaceSlugSettingsWhiteLabelRoute:
      DashboardWorkspaceSlugSettingsWhiteLabelRoute,
    DashboardWorkspaceSlugPostsIndexRoute:
      DashboardWorkspaceSlugPostsIndexRoute,
    DashboardWorkspaceSlugSettingsIndexRoute:
      DashboardWorkspaceSlugSettingsIndexRoute,
    DashboardWorkspaceSlugPostsCampaignsCampaignIdRoute:
      DashboardWorkspaceSlugPostsCampaignsCampaignIdRoute,
  }

const DashboardWorkspaceSlugRouteWithChildren =
  DashboardWorkspaceSlugRoute._addFileChildren(
    DashboardWorkspaceSlugRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardWorkspaceSlugRoute: typeof DashboardWorkspaceSlugRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardWorkspaceSlugRoute: DashboardWorkspaceSlugRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface AdminRouteChildren {
  AdminApiKeysRoute: typeof AdminApiKeysRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminLoginsRoute: typeof AdminLoginsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWebhooksRoute: typeof AdminWebhooksRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminWorkspacesWorkspaceIdRoute: typeof AdminWorkspacesWorkspaceIdRoute
  AdminWorkspacesIndexRoute: typeof AdminWorkspacesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApiKeysRoute: AdminApiKeysRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminLoginsRoute: AdminLoginsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWebhooksRoute: AdminWebhooksRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminWorkspacesWorkspaceIdRoute: AdminWorkspacesWorkspaceIdRoute,
  AdminWorkspacesIndexRoute: AdminWorkspacesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiV1CampaignsRouteChildren {
  ApiV1CampaignsIdRoute: typeof ApiV1CampaignsIdRoute
}

const ApiV1CampaignsRouteChildren: ApiV1CampaignsRouteChildren = {
  ApiV1CampaignsIdRoute: ApiV1CampaignsIdRoute,
}

const ApiV1CampaignsRouteWithChildren = ApiV1CampaignsRoute._addFileChildren(
  ApiV1CampaignsRouteChildren,
)

interface ApiV1MediaRouteChildren {
  ApiV1MediaIdRoute: typeof ApiV1MediaIdRoute
}

const ApiV1MediaRouteChildren: ApiV1MediaRouteChildren = {
  ApiV1MediaIdRoute: ApiV1MediaIdRoute,
}

const ApiV1MediaRouteWithChildren = ApiV1MediaRoute._addFileChildren(
  ApiV1MediaRouteChildren,
)

interface ApiV1PostsRouteChildren {
  ApiV1PostsIdRoute: typeof ApiV1PostsIdRoute
}

const ApiV1PostsRouteChildren: ApiV1PostsRouteChildren = {
  ApiV1PostsIdRoute: ApiV1PostsIdRoute,
}

const ApiV1PostsRouteWithChildren = ApiV1PostsRoute._addFileChildren(
  ApiV1PostsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  AdminRoute: AdminRouteWithChildren,
  HealthzRoute: HealthzRoute,
  OnboardingRoute: OnboardingRoute,
  BioHandleRoute: BioHandleRoute,
  CTokenRoute: CTokenRoute,
  DigestUnsubscribeRoute: DigestUnsubscribeRoute,
  LSlugRoute: LSlugRoute,
  ReviewTokenRoute: ReviewTokenRoute,
  ApiAccountExportRoute: ApiAccountExportRoute,
  ApiActivityExportRoute: ApiActivityExportRoute,
  ApiAiGenerateRoute: ApiAiGenerateRoute,
  ApiAiHashtagsRoute: ApiAiHashtagsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMediaUploadRoute: ApiMediaUploadRoute,
  ApiNotificationsUnreadCountRoute: ApiNotificationsUnreadCountRoute,
  ApiPostsExportRoute: ApiPostsExportRoute,
  ApiReportsAnalyticsRoute: ApiReportsAnalyticsRoute,
  ApiV1AccountsRoute: ApiV1AccountsRoute,
  ApiV1AnalyticsRoute: ApiV1AnalyticsRoute,
  ApiV1CampaignsRoute: ApiV1CampaignsRouteWithChildren,
  ApiV1MediaRoute: ApiV1MediaRouteWithChildren,
  ApiV1PostsRoute: ApiV1PostsRouteWithChildren,
  ApiAdminQueuesSplatRoute: ApiAdminQueuesSplatRoute,
  ApiAdminUsersExportRoute: ApiAdminUsersExportRoute,
  ApiBillingWebhookProviderRoute: ApiBillingWebhookProviderRoute,
  ApiCalendarTokenIcsRoute: ApiCalendarTokenIcsRoute,
  ApiOauthCallbackPlatformRoute: ApiOauthCallbackPlatformRoute,
  ApiV1OpenapiJsonRoute: ApiV1OpenapiJsonRoute,
  ApiAdminQueuesIndexRoute: ApiAdminQueuesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
